name: Build and Publish # name of the workflow
on: push   
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "hello-wrold"
      - name: Checkout Repo_A
        uses: actions/checkout@v2