name: Build and Publish # name of the workflow

on: #Specifies the events that trigger the workflow.
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output
        run: echo "Workflow is running!"
      - name: Checkout Repo_A
        uses: actions/checkout@v2

      # - name: Build and Publish Docker Image
      #   env:
      #     AWS_REGION: us-east-1  # Example AWS region
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     ECR_REPO_URI: <your-ecr-repository-uri>  # Replace with your ECR repository URI

      #   run: 
      #     echo "testing working"
      #     # Log in to Amazon ECR
      #     aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO_URI }}

      #     # Build the Docker image
      #     docker build -t my-docker-image .

      #     # Tag the Docker image
      #     docker tag my-docker-image:latest ${{ env.ECR_REPO_URI }}/my-docker-image:latest

      #     # Push the Docker image to Amazon ECR
      #     docker push ${{ env.ECR_REPO_URI }}/my-docker-image:latest

      # - name: Trigger Workflow in Repo B
      #   uses: octokit/request-action@v2.x
      #   with:
      #     route: POST /repos/:owner/:repo/actions/workflows/:workflow_id/dispatches
      #     owner: ashrafalih
      #     repo: Repo_B
      #     workflow_id: 6945091148 
      #     ref: ${{ github.event.after }}
      #     inputs: |
      #       branch_name: ${{ github.event.ref }}
      #       docker_image_tag: ${{ github.sha }}