name : Build_and_Publish
on: push # this 'on' keyword is use to trigger the event "push" mean the pipeline will run for the push events
jobs:
  print-hello-world: #defined name of the job
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "hello-wrold"