name: Build and Publish # name of the workflow
on:
  push:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo_A
        uses: actions/checkout@v2
      - name: Build and Publish Docker Image
        env:
          AWS_REGION: us-east-1  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # ECR_REPO_URI: <your-ecr-repository-uri>  
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws/f9x9k0v4
          docker build -t test-package-mgmt-160-rc .
          # Tag the Docker image
          docker tag test-package-mgmt-160-rc:latest public.ecr.aws/f9x9k0v4/package-mgmt-repo:latest
          # Push the Docker image to Amazon ECR
          docker push public.ecr.aws/f9x9k0v4/package-mgmt-repo:latest

